# SwiftLint 0.23

included:
  - src

disabled_rules:
  - block_based_kvo # Swift 4
  - line_length
  - todo

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - sorted_imports
  - single_test_class
  - strict_fileprivate
  - switch_case_on_newline
#  - trailing_closure # Bug: realm/SwiftLint#1754
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
