language: objective-c
osx_image: xcode8.3

jobs:
  include:
    # testing
    - script: xcodebuild -workspace Vienna.xcworkspace -scheme Vienna test | xcpretty

    # linting
    - before_script: swiftlint version
      script: swiftlint --lenient --reporter emoji

notifications:
  webhooks:
    urls:
    on_failure: always
    on_start: never
