files:
  - source: /Localizations/en.xliff
    translation: /Localizations/%two_letters_code%.xliff
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        zh-CN: zh-Hans
        zh-TW: zh-Hant
